language: node_js
node_js:
- '0.11'
- '0.10'
deploy:
  provider: npm
  email: mc.s.pain.how.er+npm@gmail.com
  api_key:
    secure: Ayt0MzhTGxNOVjGgiZ+iBaAQRuOUmY9IWRC8Bz5UJgmt7S3cSxQOr0eFrZSzLqvwe4APSH+CO+ZvCjzS+fQx2syUXj9JZGJZ7Y7IwsYWPY8E7pc9oqnLB79xC9i3XEBeMNerWx4dIyYSk0k4+IRfI7Rh8gMPtrFojPYpubWKhGQ=
