language: node_js
node_js:
- '0.11'
- '0.10'
deploy:
  provider: npm
  email: mc.s.pain.how.er+npm@gmail.com
  api_key:
    secure: yVjUp7ddssEc8cArO0S377rZuow2ZooveuT3sWxeCRXsHq2FlyxSqQUh3voeg9YjJDKI+iO8HXphaZwV7PI6Xgh7eoEi7WjPi1aenPnjeaIsrm9NQwZppmX+nv9YMEctJj2KGd1WUuJbexkZurJKH94WrBhuZM9vafVE7FjA8z4=
